import 'ts-node/register/transpile-only';
import * as fs from 'fs';
import * as path from 'path';

// Preconfigure module aliasing to avoid pulling Hardhat at runtime
// eslint-disable-next-line @typescript-eslint/no-var-requires
const moduleAlias = require('module-alias');
moduleAlias.addAlias('hardhat', 'ethers');

const ROOT = path.resolve(__dirname, '../../../../');
const PKG_ROOT = path.resolve(__dirname, '../..');
const CURRENCIES_DIR = path.join(PKG_ROOT, 'currencies');

function ensureDir(dir: string) {
  if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true });
}

export async function extractCurrencies(): Promise<void> {
  ensureDir(CURRENCIES_DIR);

  // Import Currency from protocolUtils (uses ethers under the hood)
  const { Currency } = require(path.join(ROOT, 'utils', 'protocolUtils'));

  // Build code -> hash and hash -> code mappings
  const codeToHash: Record<string, string> = {};
  const hashToCode: Record<string, string> = {};

  for (const [code, hash] of Object.entries<string>(Currency)) {
    const lowerHash = hash.toLowerCase();
    codeToHash[code] = lowerHash;
    hashToCode[lowerHash] = code;
  }

  // Write currencies.json
  const currenciesJson = {
    generatedAt: new Date().toISOString(),
    codeToHash,
    hashToCode
  };
  fs.writeFileSync(
    path.join(CURRENCIES_DIR, 'currencies.json'),
    JSON.stringify(currenciesJson, null, 2)
  );

  // Write types.d.ts
  const typesContent = `// Auto-generated type definitions for currency configurations

export interface CurrencyLookups {
  generatedAt: string;
  codeToHash: Record<string, string>;
  hashToCode: Record<string, string>;
}
`;
  fs.writeFileSync(path.join(CURRENCIES_DIR, 'types.d.ts'), typesContent);

  // Write index.ts
  const indexContent = `// Auto-generated by extract-all.ts
// Currency code <-> keccak256 hash lookups

import type { CurrencyLookups } from './types';
export type { CurrencyLookups };

export { default as currencies } from './currencies.json';
`;
  fs.writeFileSync(path.join(CURRENCIES_DIR, 'index.ts'), indexContent);

  // Write index.d.ts
  const indexDts = `// Typed re-exports for currencies
export { default as currencies } from './currencies';
`;
  fs.writeFileSync(path.join(CURRENCIES_DIR, 'index.d.ts'), indexDts);

  // Write currencies.d.ts for the JSON file
  const currenciesDts = `// Typed currencies file
export type CurrencyData = { generatedAt: string; codeToHash: Record<string, string>; hashToCode: Record<string, string> };
declare const value: CurrencyData;
export default value;
`;
  fs.writeFileSync(path.join(CURRENCIES_DIR, 'currencies.d.ts'), currenciesDts);

  console.log(`✅ Currency lookups written to ${CURRENCIES_DIR}`);
}
