import 'ts-node/register/transpile-only';
import * as fs from 'fs';
import * as path from 'path';

// Preconfigure module aliasing to avoid pulling Hardhat at runtime
// eslint-disable-next-line @typescript-eslint/no-var-requires
const moduleAlias = require('module-alias');
moduleAlias.addAlias('hardhat', 'ethers');

const PKG_ROOT = path.resolve(__dirname, '../..');
const ORACLE_DIR = path.join(PKG_ROOT, 'oracleFeeds');

function ensureDir(dir: string) {
  if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true });
}

export async function extractOracleFeeds(): Promise<void> {
  ensureDir(ORACLE_DIR);

  const {
    CHAINLINK_FEEDS,
  } = require(path.join(__dirname, '..', 'data', 'oracleFeeds'));

  // Write chainlink.json
  const chainlinkJson = {
    generatedAt: new Date().toISOString(),
    network: 'base',
    feeds: CHAINLINK_FEEDS,
  };
  fs.writeFileSync(
    path.join(ORACLE_DIR, 'chainlink.json'),
    JSON.stringify(chainlinkJson, null, 2)
  );

  // Write types.d.ts
  const typesContent = `// Auto-generated type definitions for oracle feed configurations

export interface ChainlinkFeed {
  pair: string;
  feed: string;
  decimals: number;
}

export interface ChainlinkFeeds {
  generatedAt: string;
  network: string;
  feeds: ChainlinkFeed[];
}
`;
  fs.writeFileSync(path.join(ORACLE_DIR, 'types.d.ts'), typesContent);

  // Write index.ts
  const indexContent = `// Auto-generated by extract-all.ts
// Oracle feed configurations (Chainlink only — Pyth removed 2026-03-17)

import type { ChainlinkFeed, ChainlinkFeeds } from './types';
export type { ChainlinkFeed, ChainlinkFeeds };

export { default as chainlink } from './chainlink.json';
`;
  fs.writeFileSync(path.join(ORACLE_DIR, 'index.ts'), indexContent);

  // Write index.d.ts
  const indexDts = `// Typed re-exports for oracle feeds
export type { ChainlinkFeed, ChainlinkFeeds } from './types';
export { default as chainlink } from './chainlink';
`;
  fs.writeFileSync(path.join(ORACLE_DIR, 'index.d.ts'), indexDts);

  // Write chainlink.d.ts for the JSON file
  const chainlinkDts = `// Typed chainlink feeds file
import type { ChainlinkFeeds } from './types';
declare const value: ChainlinkFeeds;
export default value;
`;
  fs.writeFileSync(path.join(ORACLE_DIR, 'chainlink.d.ts'), chainlinkDts);

  // Remove pyth files if they exist
  const pythFiles = ['pyth.json', 'pyth.d.ts'];
  for (const f of pythFiles) {
    const p = path.join(ORACLE_DIR, f);
    if (fs.existsSync(p)) fs.unlinkSync(p);
  }

  console.log(`✅ Oracle feed configs written to ${ORACLE_DIR} (Chainlink only)`);
}
