import 'ts-node/register/transpile-only';
import * as fs from 'fs';
import * as path from 'path';

// Preconfigure module aliasing to avoid pulling Hardhat at runtime
// eslint-disable-next-line @typescript-eslint/no-var-requires
const moduleAlias = require('module-alias');
moduleAlias.addAlias('hardhat', 'ethers');

const PKG_ROOT = path.resolve(__dirname, '../..');
const ORACLE_DIR = path.join(PKG_ROOT, 'oracleFeeds');

function ensureDir(dir: string) {
  if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true });
}

export async function extractOracleFeeds(): Promise<void> {
  ensureDir(ORACLE_DIR);

  const {
    CHAINLINK_FEEDS,
    PYTH_FEEDS,
    PYTH_KEEPER_FEED_IDS,
    PYTH_CONTRACTS,
  } = require(path.join(__dirname, '..', 'data', 'oracleFeeds'));

  // Write chainlink.json
  const chainlinkJson = {
    generatedAt: new Date().toISOString(),
    network: 'base',
    feeds: CHAINLINK_FEEDS,
  };
  fs.writeFileSync(
    path.join(ORACLE_DIR, 'chainlink.json'),
    JSON.stringify(chainlinkJson, null, 2)
  );

  // Write pyth.json
  const pythJson = {
    generatedAt: new Date().toISOString(),
    feeds: PYTH_FEEDS,
    keeperFeedIds: PYTH_KEEPER_FEED_IDS,
    contracts: PYTH_CONTRACTS,
  };
  fs.writeFileSync(
    path.join(ORACLE_DIR, 'pyth.json'),
    JSON.stringify(pythJson, null, 2)
  );

  // Write types.d.ts
  const typesContent = `// Auto-generated type definitions for oracle feed configurations

export interface ChainlinkFeed {
  pair: string;
  feed: string;
  decimals: number;
}

export interface ChainlinkFeeds {
  generatedAt: string;
  network: string;
  feeds: ChainlinkFeed[];
}

export interface PythFeed {
  pair: string;
  feedId: string;
  decimals: number;
}

export interface PythFeeds {
  generatedAt: string;
  feeds: PythFeed[];
  keeperFeedIds: string[];
  contracts: Record<string, string>;
}
`;
  fs.writeFileSync(path.join(ORACLE_DIR, 'types.d.ts'), typesContent);

  // Write index.ts
  const indexContent = `// Auto-generated by extract-all.ts
// Oracle feed configurations for Chainlink and Pyth

import type { ChainlinkFeeds, PythFeeds } from './types';
export type { ChainlinkFeed, ChainlinkFeeds, PythFeed, PythFeeds } from './types';

export { default as chainlink } from './chainlink.json';
export { default as pyth } from './pyth.json';
`;
  fs.writeFileSync(path.join(ORACLE_DIR, 'index.ts'), indexContent);

  // Write index.d.ts
  const indexDts = `// Typed re-exports for oracle feeds
export type { ChainlinkFeed, ChainlinkFeeds, PythFeed, PythFeeds } from './types';
export { default as chainlink } from './chainlink';
export { default as pyth } from './pyth';
`;
  fs.writeFileSync(path.join(ORACLE_DIR, 'index.d.ts'), indexDts);

  // Write chainlink.d.ts for the JSON file
  const chainlinkDts = `// Typed chainlink feeds file
import type { ChainlinkFeeds } from './types';
declare const value: ChainlinkFeeds;
export default value;
`;
  fs.writeFileSync(path.join(ORACLE_DIR, 'chainlink.d.ts'), chainlinkDts);

  // Write pyth.d.ts for the JSON file
  const pythDts = `// Typed pyth feeds file
import type { PythFeeds } from './types';
declare const value: PythFeeds;
export default value;
`;
  fs.writeFileSync(path.join(ORACLE_DIR, 'pyth.d.ts'), pythDts);

  console.log(`\u2705 Oracle feed configs written to ${ORACLE_DIR}`);
}
