import 'ts-node/register/transpile-only';
import * as fs from 'fs';
import * as path from 'path';

const ROOT = path.resolve(__dirname, '../../../../');
const PKG_ROOT = path.resolve(__dirname, '../..');
const UTILS_DIR = path.join(PKG_ROOT, 'utils');

function ensureDir(dir: string) {
  if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true });
}

export async function extractUtils(): Promise<void> {
  ensureDir(UTILS_DIR);
  
  for (const utility of ['protocolUtils.ts']) {
    const sourceFile = path.join(ROOT, 'utils', utility);
    const destFile = path.join(UTILS_DIR, utility);
    fs.copyFileSync(sourceFile, destFile);
  }
  
  // Create index file for clean exports
  const indexContent = `// Auto-generated by extract-all.ts
// Protocol utilities export

export * from './protocolUtils';

// Re-export commonly used items for convenience
export { 
  Currency, 
  getKeccak256Hash, 
  getCurrencyCodeFromHash,
  calculateIntentHash
} from './protocolUtils';
`;
  
  fs.writeFileSync(
    path.join(UTILS_DIR, 'index.ts'),
    indexContent
  );
  
  console.log(`✅ Utils written to ${UTILS_DIR}`);
}
